# Generated by Django 5.2.3 on 2025-06-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderServices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
