# Generated by Django 5.2.3 on 2025-06-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderServices", "0002_alter_order_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="billing_address",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
