# Generated by Django 5.2.3 on 2025-06-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderServices", "0003_alter_order_billing_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
