# Generated by Django 5.2.3 on 2025-06-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orderServices", "0004_alter_order_total_amount"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orderServic_user_id_8f4ded_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orderstatushistory",
            name="created_by",
        ),
        migrations.AddField(
            model_name="order",
            name="user_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="orderstatushistory",
            name="created_by_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user_id", "-created_at"], name="orderServic_user_id_8f4ded_idx"
            ),
        ),
    ]
