# Generated by Django 5.1.2 on 2024-10-28 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("roles", models.ManyToManyField(blank=True, to="userservices.role")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(max_length=255)),
                ("expiring_at", models.DateTimeField()),
                (
                    "session_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("EXPIRED", "EXPIRED"),
                            ("LOGGED_OUT", "LOGGED_OUT"),
                            ("INVALID", "INVALID"),
                        ],
                        default="ACTIVE",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="userservices.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
