# Generated by Django 5.1.2 on 2024-10-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userservices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_status",
            field=models.CharField(
                choices=[("A", "C"), ("E", "X"), ("L", "O"), ("I", "N")],
                default="A",
                max_length=50,
            ),
        ),
    ]
