# Generated by Django 5.1.2 on 2024-11-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userservices", "0003_alter_session_session_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_status",
            field=models.CharField(
                choices=[("A", "c"), ("E", "x"), ("L", "o"), ("I", "n")],
                default="A",
                max_length=50,
            ),
        ),
    ]
