# Generated by Django 5.1.1 on 2024-11-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userservices", "0005_alter_user_options_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name="role",
            table="role",
        ),
    ]
