# Generated by Django 5.1.3 on 2025-06-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="inventory_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
