# Generated by Django 5.1.3 on 2025-06-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0002_product_inventory_count_alter_product_product_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="title",
            field=models.CharField(default="Unnamed Product", max_length=255),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
